#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
load_struct_testing_wget(){
    local provider="/_/clis/execute_command_intuivo_cli/struct_testing"
    [   -e "${provider}"  ] && source "${provider}"
    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
} # end load_struct_testing_wget
load_struct_testing_wget

load_execute_command_wget(){
    local provider="/_/clis/execute_command_intuivo_cli/execute_command"
    [   -e "${provider}"  ] && source "${provider}"
    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_command -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading execute_command \n \n " && exit 69; )
} # end load_execute_command_wget
load_execute_command_wget


patch_chrome_alone() {
    anounce About to do 2 things:
    anounce   0. Patch Horrible Google Spaced Folder
    anounce   1. Chrome Fail and fix 
    anounce   2. Followup Complete Coherence Fix:
    anounce   - start - 
    say 0. Patch Horrible Google Spaced Folder
    GOOGLEPATH="Google Chrome.app"
    GOOGLEPATHPATCHED=$(sed 's/ /_/g' <<< "${GOOGLEPATH}")
    anounce cd /Applications
    cd /Applications
    unlink "${GOOGLEPATHPATCHED}"
    directory_exists_with_spaces "/Applications/${GOOGLEPATH}"
    does_not_exist_with_spaces "/Applications/${GOOGLEPATHPATCHED}"
    anounce ln -P "${GOOGLEPATHPATCHED}" "/Applications/Google\ Chrome.app" 
    ln -s "/Applications/Google Chrome.app/" "${GOOGLEPATHPATCHED}" 
    anounce_command ls -la "/Applications/${GOOGLEPATHPATCHED}"
    softlink_exists "/Applications/${GOOGLEPATHPATCHED}"

    say 1. Chrome Fail and fix --

    GOOGLECONTENTSPATH="/Applications/${GOOGLEPATHPATCHED}/Contents"
    anounce_command ls  -la "${GOOGLECONTENTSPATH}"
    say Then I created the folder using sudo:
    sudo rm -rf "${GOOGLECONTENTSPATH}/Profile"
    echo '#' | anounce_command sudo mkdir "${GOOGLECONTENTSPATH}/Profile"
    directory_exists "${GOOGLECONTENTSPATH}/Profile"
    directory_exists_with_spaces $(realpath "${GOOGLECONTENTSPATH}/Profile")

    say Then I create the softlink using sudo:
    directory_exists_with_spaces ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts
    sudo ln -fs ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts /Applications/Google\ Chrome.app/Contents/Profile/NativeMessagingHosts
    softlink_exists_with_spaces "/Applications/Google Chrome.app/Contents/Profile/NativeMessagingHosts"
}



say 2. Followup Complete Coherence Fix --- 


exit

directory_exists "
/Applications/Google\ Chrome.app/Contents/Profile
"

echo "sudo mkdir  /Applications/Google\ Chrome.app/Contents/Profile
"