#!/usr/bin/env bash
#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
load_struct_testing_wget(){
    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
    [   -e "${provider}"  ] && source "${provider}"
    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
} # end load_struct_testing_wget
load_struct_testing_wget

               _fedora__64(){ ag_fedora_64 "$@"}
  #              _fedora__32(){ }
               _ubuntu__64(){ ag_ubuntu_64 "$@"}
               _ubuntu__32(){ ag_ubuntu_32 "$@"}
               _mingw__64(){ ag_win_64 "$*" }
  #              _mingw__32(){ }
               _darwin__64(){ ag_mac_64 "$@"}
               _darwin__32(){ ag_mac_32 "$@" }

determine_os_and_fire_action
