#!/usr/bin/env bash
#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#

while read -r ONE ; do
echo """$ONE""" | sed 's/o/ /g'
echo """$ONE""" | sed 's/o/ /g'
done <<< """$(figlet -f banner $1 | sed 's/ /o/g')"""