#!/usr/bin/env bash
#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#

while read -r ONE ; do
echo """$ONE""" | sed 's/o\|p\|\.\|_/ /g'
echo """$ONE""" | sed 's/o\|p\|\.\|_/ /g'
done <<< """$(figlet -f banner $1 \
| sed 's/ /o/g' \
| sed 's/#oooooo/#_____.pppp/g' \
| sed 's/ooooo#o/_____#.pppp/g' \
| sed 's/#####oo/#####_.pppp/g' \
| sed 's/#oooo#o/#____#.pppp/g' \
| sed 's/o#oo#oo/_#__#_.pppp/g' \
| sed 's/oo##ooo/__##__.pppp/g' \
| sed 's/o####oo/_####_.pppp/g' \
| sed 's/######o/######.pppp/g' \
| sed 's/#oo###o/#__###.pppp/g' \
| sed 's/o#ooooo/_#____.pppp/g' \
| sed 's/oo#oooo/__#___.pppp/g' \
| sed 's/ooo#ooo/___#__.pppp/g' \
| sed 's/oooo#oo/____#_.pppp/g' \
| sed 's/#ooo#oo/#___#_.pppp/g' \
| sed 's/\.pppp#o/_pppp##.pppp/g' \
| sed s/#/##/g \
| sed 's/o\|p\|\.\|_/oo/g' \
)"""