#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
# ref http://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-ps1-prompt


color=1;
while [ $color -lt 3 ]; do
	count=1;
	echo "ALO"
	while [ $count -lt 3 ]; do
		echo "HOLA"
		break;
		echo "WELCOME"
		((count++));
	done
	((color++));
done

#exit 0;

color=16;
while [ $color -lt 256 ]; do
    echo -e "$color: \\033[38;5;${color}mhello\\033[48;5;${color}mworld\\033[0m echo -e \"\\\\033[38;5;${color}m FOREGROUND   \"; echo -e \"\\\\033[48;5;${color}m BACKGROUND   \""
    ((color++));
done

color=1;
echo " #####################   tput   #################### "
echo " #####################   tput   #################### "
echo " #####################   tput   #################### "
echo " #####################   tput   #################### "
echo " #####################   tput   #################### "
echo " #####################   tput   #################### "

while [ $color -lt 256 ]; do
	thiscolor=$(tput setaf ${color})
	echo -e "$color: ${thiscolor} SIMPLE \\033[38;5;${color}mhello\\033[48;5;${color}mworld\\033[0m echo -e \"\\\\033[38;5;${color}m FOREGROUND   \"; echo -e \"\\\\033[48;5;${color}m BACKGROUND   \""
    ((color++));
done
