#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


# if value is not set  -- exit silent it
if [[ -z "$1"  ]] ; then
    exit 0
fi

# Escape chars / !
function escape_slashes {
    sed 's/\//\\\//g'
}
function escape_quotes {
    sed 's/\"/\\\"/g'
}
function escape_bangs {
    sed 's/\!/\\\!/g'
}
function escape_dots {
    sed 's/\./\\\./g'
}
SEEKING=$(echo """$*"""  | escape_dots | escape_slashes | escape_quotes | escape_bangs)



# if everything else --

# check operation systems
(
  if [[ "$(uname)" == "Darwin" ]] ; then
    # Do something under Mac OS X platform
    sed 's/'"""${SEEKING}"""'//g' ;
  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
    # Do something under GNU/Linux platform
    sed 's/'"""${SEEKING}"""'//g'  ;

  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] || [[ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]] ; then
    # Do something under Windows NT platform
    sed 's/'"""${SEEKING}"""'//g' ;
    # nothing here
  fi
)

