#!/usr/bin/env bash
#!/bin/bash

sudo dnf update -vy &
flatpak update -y &
# snap refresh
brew unlink php &
composer global update &
brew update
wait
brew upgrade &

mix archive.install hex phx_new &
gem update &

flutter upgrade &
rustup upgrade &
 
cd $HOME/_/clis/ && pull_all_subdirectories

