#!/usr/bin/env bash
#!/bin/bash

function run_fedora_update() {
  local -i _err=0
  local -i _cron_running=1
  function exit_updateSelf() {
  	echo "${0} ${FUNCNAME[0]} EXIT"
  	if [ ${_cron_running-} -ne 0 ] ; then
  	{
      exec 1>&3 2>&4 # How to redirect output  REF: https://stackoverflow.com/questions/314675/how-to-redirect-output-of-an-entire-shell-script-within-the-script-itself
    }
    else
    {
      exec 1>&3  # How to redirect output  REF: https://stackoverflow.com/questions/314675/how-to-redirect-output-of-an-entire-shell-script-within-the-script-itself
    }
    fi
  }
  trap exit_updateSelf EXIT

  ( # subprocess
    cd $HOME/_/clis/ && pull_all_subdirectories &
  )

  cd

  function update_snaps(){
    local _snaps=""
    _snaps="$(sudo snap list | grep -v 'Name' | cut -d' '  -f1)"
    wait
    echo "snaps: ${_snaps}"
    local _one=""
    while read -r _one ; do
    {
      [[ -z "${_one}" ]] && continue
      echo "Checking  ${_one}"
      echo sudo pkill "${_one}"
      sudo pkill "${_one}"
      wait
      echo sudo  snap refresh "${_one}"
      sudo snap refresh "${_one}"
      wait
    }
    done <<< "${_snaps}"

  } # end update_snaps
	git -C "$(rbenv root)"/plugins/ruby-build pull
	git -C "$(pyenv root)"/plugins/ruby-build pull
  echo "snaps"
  update_snaps &
  sudo dnf update -vy &
  flatpak update -y &
  # snap refresh
  brew unlink php &
	cd  /home/zeus/.config/composer/vendor/nesbot/carbon
	git checkout bin/carbon
  yes | composer global update &
	cd  /home/zeus/.config/composer/vendor/nesbot/carbon 
	git checkout bin/carbon
	yes | composer global update &
  brew update
  wait
  brew upgrade &

  mix archive.install hex phx_new &
  gem update &

  flutter upgrade &
  rustup upgrade &

}

run_fedora_update

