#!/bin/bash
# @author Zeus Intuivo <zeus@intuivo.com>
#

#
.each() {
  # Sample usage:
  # ALL_REMOTE_BRANCHES_BRANCHES=$(git branch -r --no-color | sed '1d' | sed 's/[*]//g' | sed 's/\ //g' )
  # ACTIONS="git checkout {#}
  # pull
  # "
  # .each  "${ACTIONS}" "${ALL_REMOTE_BRANCHES_BRANCHES_WITHOUT_ORIGIN}"

  local local_actions="${1}"
  local local_items="${2}"
  local one_item
  local one_action
  local action

  while read -r one_item; do                                                  # Get longest file name
  {
    if [ ! -z "${one_item}" ] ; then  # if not empty
    {
      while read -r one_action; do                                                  # Get longest file name
      {
        if [ ! -z "${one_action}" ] ; then  # if not empty
        {
          action="${one_action/\{\#\}/$one_item}"  # replace value inside string substitution expresion bash
          eval ${action}
        }
        fi
      }
      done <<< "${local_actions}"
    }
    fi
  }
  done <<< "${local_items}"
}

THISSCRIPTNAME=`basename "$0"`
                          function trim_start_space() {
                              sed -e 's/^[[:space:]]*//' | sed 's/^\ //g' | sed 's/^\t//g'
                          }
#bash shell script check input argument
if [ -z "$1" ] ; then
{
    SEEKING="filename"
    echo " "
    echo "${THISSCRIPTNAME}. Finds a filename using 'find' from linux/mac and 'ag' "
    echo " "
    echo "Command used locating: \"${SEEKING}\" "
    echo -e "\033[38;5;214m === find . | ag --nocolor \"/.*${SEEKING}[^/]*$\" | sed 's/../  /' ===\n \033[38;5;189m";
    echo " "
    echo "Missing 1st argument "
    echo " "
    echo "Sample Usage:    - expects one argument "
    echo " "
    echo "    ${THISSCRIPTNAME}  this "
    echo "    ";
    exit
}
fi
SEEKING="$1";
PARAMS="";
if [ -z "$2" ]
  then
  {
  	PARAMS="$2";
  }
fi
#echo $0=./replace
#echo -e "\033[38;5;147m "
#echo " "
#echo " "
#echo " ";
#echo -e "\033[38;5;214m === find . | ag --nocolor \"/.*${SEEKING}[^/]*$\" | sed 's/../  /' ===\n \033[38;5;189m";
#echo " ";
## SED REF: http://www.theunixschool.com/2014/08/sed-examples-remove-delete-chars-from-line-file.html
#                                           # remove 1st character in every line:
# echo "err_buff3=$?"
findings=$(find . | ag --nocolor "/.*${SEEKING}[^/]*$" | trim_start_space | sed 's/^\../  /g')
# echo "err_buff4=$?"
if [[ ! -z "${findings}" ]] ; then
{
  # echo "err_buff5=$?"
  #ACTIONS="echo -e \"{#}\\033[38;5;232m:1\\033[0m\""
  ACTIONS="echo \"{#}\""
  # echo "err_buff6=$?"
  if [ -d .idea/ ] && [ -f Gemfile ] && [ -d app/ ] && [ -d db/ ] && [ -d config/ ] && [ -d "test/" ] ; then 
    ACTIONS="echo -e \"\\033[38;5;202m{#}\\033[38;5;232m:1\""
  fi   
  # echo "err_buff7=$?"
  .each  "${ACTIONS}"  "${findings}"
  # echo "err_buff8=$?" 
}
fi


# echo -e " "
