#!/bin/bash
# @author Zeus Intuivo <zeus@intuivo.com>
#
#!/usr/bin/env bash
# set -euo pipefail


function do_gefund() {


  trim_start_space() {
    sed -e 's/^[[:space:]]*//' \
      -e 's/^\ //g' \
      -e 's/^\t//g'
  } # end trim_start_space

  trim_first_dot_from_find_style_list() {
    sed 's/^\..//g'
  } # end trim_first_dot_from_find_style_list

  # local ACTIONS=""
  local ACTIONS=('echo "{#}"')
  # if you detect a Rails-ish project, use colours
  if [[ -d .idea && -f Gemfile && -d app && -d db && -d config && -d test ]]; then
  {
    ACTIONS=('echo -e "\033[38;5;202m{#}\033[38;5;232m:1\033[0m"')
  }
  fi
  function escape_parenthesis_right {
		sed 's/[)]/\\\)/g'
  }

 function escape_parenthesis_left {
		sed 's/[(]/\\\(/g'
  }

 function escape_spaces {
		sed 's/\ /\\\ /g'
  }

  .each() {
	  function _trap_on_error(){
    local -ir __trapped_error_exit_num="${2:-0}"
    echo -e "\\n \033[01;7m*** 0tasks_base/sudoer.bash:$LINENO load_struct_testing() ERROR TRAP $THISSCRIPTNAME \\n${BASH_SOURCE}:${BASH_LINENO[-0]} ${FUNCNAME[1]}() \\n$0:${BASH_LINENO[1]} ${FUNCNAME[2]}()  \\n$0:${BASH_LINENO[2]} ${FUNCNAME[3]}() \\n ERR ...\033[0m  \n \n "

    echo ". ${1}"
    echo ". exit  ${__trapped_error_exit_num}  "
    echo ". caller $(caller) "
    echo ". ${BASH_COMMAND}"
    local -r __caller=$(caller)
    local -ir __caller_line=$(echo "${__caller}" | cut -d' ' -f1)
    local -r __caller_script_name=$(echo "${__caller}" | cut -d' ' -f2)
    awk 'NR>L-10 && NR<L+10 { printf "%-10d%10s%s\n",NR,(NR==L?"☠ » » » > ":""),$0 }' L="${__caller_line}" "${__caller_script_name}"

    # $(eval ${BASH_COMMAND}  2>&1; )
    # echo -e " ☠ ${LIGHTPINK} Offending message:  ${__bash_error} ${RESET}"  >&2
    exit 1
  }
	   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR INT
    local one_item=""
    local act=""
    local cmd=""
    while IFS= read -r one_item; do
    {
        [[ -z "${one_item}" ]] && continue
        for act in "${ACTIONS[@]}"; do
        {
					# DEBUG echo ">>>"
					# DEBUG echo  "${one_item}"
					local escaped="$(escape_spaces <<< "${one_item}" | escape_parenthesis_left | escape_parenthesis_right )"
					# DEBUG echo "===="
          cmd="${act//\{\#\}/"${escaped}"}"
          # BROKE cmd="${act//\{\#\}/"${one_item}"}" # CASE echo ""text (1).pdf" = syntax error near unexpected token `('
					# DEBUG echo "----"
					# DEBUG echo  "${cmd}"
					# DEBUG echo "<<<"
          eval "${cmd}"
        }
        done
    }
    done
  } # end .each

  local SEEKING="${*}"

  local MOREIGNORE_FILES=""
  local MOREIGNORE_DIRS=""
  # your per-item action(s)



  MOREIGNORE_FILES=""
  [ -f .oeignore_files ] && MOREIGNORE_FILES=$(<.oeignore_files)
  MOREIGNORE_DIRS=""
  [ -f .oeignore_dirs ] && MOREIGNORE_DIRS=$(<.oeignore_dirs)

  # echo "MOREIGNORE_FILES:${MOREIGNORE_FILES}"
  # echo "MOREIGNORE_DIRS:${MOREIGNORE_DIRS}"
  # exit 0

  FILESTOEXCLUDE=".dir_bash_history
  .gitignore
  .ersetzeignore_dirs
  .ersetzeignore_files
  .nurignore_dirs
  .nurignore_files
  .tutorial
  ack
  bootstrap.php.cache
  conflicts
  composer.phar
  countalltables
  dBug.php
  generateinserts
  generatelocations
  generateparams
  load_insert
  phpunit
  ${MOREIGNORE_FILES}"

  DIRSTOEXCLUDE=".cargo
  .nyc_output
  .serverless
  .tmp
  .ecryptfs
  .gvfs
  .git
  .idea
  .vagrant
  .servo
  coverage
  AbsoluteUrlBundle
  app/Stubs
  bower_components
  cache
  .cache
  dist
  node_modules
  python
  storage/debugbar
  storage/logs
  target
  tmp
  log
  ports
  app/Stubs
  var/cache
  var/logs
  var/session
  app/cache
  app/logs
  app/session
  ${MOREIGNORE_DIRS}"
  # echo "FILESTOEXCLUDE:${FILESTOEXCLUDE}"
  # echo "DIRSTOEXCLUDE:${DIRSTOEXCLUDE}"
  # exit 0

  IGNORELIST="node_modules"
  EXCLUDEPREFIX='|'
  while read -r ONE_FILENAME; do
    # if not empty
    if [[ -n "${ONE_FILENAME}" ]] ; then
      IGNORELIST="${IGNORELIST}${EXCLUDEPREFIX}${ONE_FILENAME}"
    fi
  done <<< "${FILESTOEXCLUDE}"
  while read -r ONE_DIRNAME; do
    # if not empty
    if [[ -n "${ONE_DIRNAME}" ]] ; then
      IGNORELIST="${IGNORELIST}${EXCLUDEPREFIX}${ONE_DIRNAME}"
    fi
  done <<< "${DIRSTOEXCLUDE}"
   #  echo "$IGNORELIST"

   #   main loop:  stream find + ag + sed + grep  →  while read; do …; done
   #
   find . \
       | ag --nocolor "/.*${SEEKING}[^/]*$" \
       | trim_first_dot_from_find_style_list \
       | grep -Ev "${IGNORELIST}" \
       | trim_start_space \
       | .each

} # en do_gefund

THISSCRIPTNAME="$(basename "$0")"
SEEKING="${*}"

# usage
if [[ $# -lt 1 ]]; then
{

    echo -e "

    ${THISSCRIPTNAME} v2 -- stream-find

    Command used locating: ${SEEKING}
    \033[38;5;214m === find . | ag --nocolor "/.*${SEEKING}[^/]*$" | sed 's/../  /' ===\n \033[38;5;189m

    Missing 1st argument

    Sample Usage:

    Usage:
      ${THISSCRIPTNAME} <pattern>

    Example:
      ${THISSCRIPTNAME} foo

    "
    exit 1
}
fi



do_gefund ${*}


# end
