#!/bin/bash

# Replace includes
#sed -i -e "/include Policies::DefaultResourcePolicy/{s/include Policies::DefaultResourcePolicy/\r < Policies::DefaultResourcePolicy/;}" app/lib/policies/*
# Join line 3 with 4
#sed -i -e "3{N; s/\n//;}" app/lib/policies/*
# Remove sed leftovers
#rm app/lib/policies/*-e

if [ ${#} -lt 1 ] ; then
{
  echo "$0 joins to line in a file

  Needs one number to know which line to join

  Samples


  echo 'hola
  hello' | joinlines 1      <- this will output line 1 plus line 2 = holahello


  joinlines 2 filename.txt  <- this will output line 2 plus line 3 in file filename.tx

  "
  exit 1
}
fi

if [[ -z "${2}" ]] ; then
{
  sed -i -e "${1}{N; s/\n//;}" "${2}"
  rm "${2}-e"
}
else
{
  #PIPING expexted
  sed -e "${1}{N; s/\n//;}"
}
fi



