#!/bin/bash
# 
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


# if everything else -- 
 
# check operation systems 
(
  if [[ "$(uname)" == "Darwin" ]] ; then 
    # Do something under Mac OS X platform    
    npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm  
  elif [[ "$(cut -c1-5 <<< "$(uname -s)")" == "Linux" ]] ; then 
    # Do something under GNU/Linux platform
    npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm
  
  elif [[ "$(cut -c1-10 <<< "$(uname -s)")" == "MINGW32_NT" ]] || [[ "$(cut -c1-10 <<< "$(uname -s)")" == "MINGW64_NT" ]] ; then 
    # Do something under Windows NT platform
    sed 's/'"""${SEEKING}"""'//g' ;
    # nothing here
  fi 
)
 
