#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


# if value is not set  -- exit silent it
if [[ -z "$1"  ]] ; then
    exit 0
fi

# Escape chars / !
function escape_slashes {
    sed 's/\//\\\//g'
}
function escape_quotes {
    sed 's/\"/\\\"/g'
}
function escape_bangs {
    sed 's/\!/\\\!/g'
}
SEEKING=$(echo """$*"""  | escape_quotes | escape_bangs)
SEEKING="""$*"""
SEEKING=$(echo """$*"""   )


# if everything else --

# check operation systems
(
  if [[ "$(uname)" == "Darwin" ]] ; then
    # Do something under Mac OS X platform
    nur """${SEEKING}""" ;
  elif [[ "$(cut -c1-5 <<< "$(uname -s)")" == "Linux" ]] ; then
    # Do something under GNU/Linux platform
    nur """${SEEKING}""" ;

  elif [[ "$(cut -c1-10 <<< "$(uname -s)")" == "MINGW32_NT" ]]  || [[ "$(cut -c1-10 <<< "$(uname -s)")" == "MINGW64_NT" ]] ; then
    # Do something under Windows NT platform
    nur """${SEEKING}""" ;
    # nothing here
  fi
)

