#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


# if value is not set  -- exit silent it
if [[ -z "$1"  ]] ; then
    exit 0
fi
if [[ -z "$2"  ]] ; then
    exit 0
fi

# Escape chars / !
function escape_slashes {
    sed 's/\//\\\//g'
}
function escape_quotes {
    sed 's/\"/\\\"/g'
}
function escape_bangs {
    sed 's/\!/\\\!/g'
}
SEEKING=$(echo """$*"""  | escape_quotes | escape_bangs)
SEEKING="""$*"""
SEEKING=$(echo """$*"""   )

FILES=$(echo """$2"""  | escape_quotes | escape_bangs)
FILES="""$2"""
FILES=$(echo """$2"""   )


# if everything else --

# check operation systems
(
  if [[ "$(uname)" == "Darwin" ]] ; then
    # Do something under Mac OS X platform
    nurindatei """${SEEKING}""" """${FILES}""";
  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
    # Do something under GNU/Linux platform
    nurindatei """${SEEKING}""" """${FILES}""";

  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
    # Do something under Windows NT platform
    nurindatei """${SEEKING}""" """${FILES}""";
    # nothing here
  fi
)

