#!/usr/bin/env bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
  if ! ( command -v realpath >/dev/null 2>&1; ) ; then # MAC  # updated realpath macos 20210924
  {
    # updated realpath macos 20210924
    export realpath    # updated realpath macos 20210924
    function realpath() { # Macos after BigSur is missing realpath  # updated realpath macos 20210924
      local _our_pwd="${PWD}"
      cd "$(dirname "${1}")" || (echo "${1}" && return 0)
      local _link=""
      _link="$(readlink "$(basename "${1}")")"
      while [ "${_link}" ]; do
        cd "$(dirname "${_link}")" || (echo "${1}" && return 0)
        _link="$(readlink "$(basename "${1}")")"
      done
      local _resolved_path=""
      _resolved_path="${PWD}/$(basename "$1")"
      cd "${_our_pwd}" || (echo "${1}" && return 0)
      echo "${_resolved_path}"
      return 0
    }
  }
  fi
  export realpath
function realpath() (
  local OURPWD=$PWD
  cd "$(dirname "$1")"
  local LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  local REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
)